function getFormGeozona() {
    return   '<form id="frmGeoZona" name="frmGeoZona" method="post">'
            + '<input type="hidden" id="txtIdGeozona" name="txtIdGeozona" />'
            + '<div class="table-responsive">'
            + '<fieldset>'            
            + '<table class="table">'
            + '<thead>'
            + '<tr>'
            + '<th colspan="6" class="dt-responsive" style="text-align: center;">'
            + '</th>'
            + '</tr>'
            + '<tbody>'
            + '<tr>'
            + '<td colspan="6">'
            + '<div id="divMapGeozona"></div>'
            + '</td>'
            + '</tr>'
            + '</tbody>'
            + '<thead>'
            + '<tr>'
            + '<th class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size">Veh&iacute;culos</label>'
            + '</th>'
            + '<th class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size"> <span class="req">*</span> Nombre Zona</label>'
            + '</th>'
            + '<th class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size">Color de la zona</label>'
            + '</th>'
            + '<tbody>'
            + '<tr>'
            + '<td>'
            + '<select class="form-control required" multiple="multiple" id="cboVehiculos" name="cboVehiculos">'
            + listVehiculos
            + '</select><label id="lblErrorSelect" style="display: none;" class="alert-danger font-size">Campo requerido</label>'
            + '</td>'
            + '<td>'
            + '<input type="text" id="txtZona" name="txtZona" class="required form-control col-xs-1 input-sm" onkeypress="mayuscula(this);" />'
            + '</td>'
            + '<td>'
            + '<p id="container"></p>'
            + '<input type="hidden" id="txtPos1" name="txtPos1"/>'
            + '<input type="hidden" id="txtPos2" name="txtPos2"/>'
            + '<input type="hidden" id="txtPos3" name="txtPos3"/>'
            + '<input type="hidden" id="txtPos4" name="txtPos4"/>'
            + '<input type="hidden" id="txtPos5" name="txtPos5"/>'
            + '</td>'
            + '</tbody>'
            + '</table>'
            + '</fieldset>'
            + '<div style="text-align:  center;">'
            + '<button type="button" class="btn" id="btnRegistrar" name="btnRegistrar">'
            + '<img src="../web/images/guardar.png" > Guardar </button>'
            + '<button type="button" class="btn" id="btnActualizar" name="btnActualizar">'
            + '<img src="../web/images/actualizar.png" > Actualizar </button>'
            + '<button type="button" class="btn" id="btnEliminar" name="btnEliminar" style="display: display;">'
            + '<img src="../web/images/eliminar.png" > Eliminar </button>'
            + '<button type="button" class="btn" id="btnAsociar" name="btnAsociar">'
            + '<img src="../web/images/vehiculoMapa.png" height="32px" width="32px;"> Asociar </button>'
            + '<button type="button" class="btn" id="btnCancel" name="btnCancel">'
            + '<img src="../web/images/cancel.png" > Cerrar </button>'
            + '</div>'
            + '</form>';
}

function getFormGeozonaUpdate() {
    return  '<form id="frmGeoZona" name="frmGeoZona" method="post">'
            + '<input type="hidden" id="txtIdGeozona" name="txtIdGeozona" />'
            + '<div class="table-responsive">'
            + '<fieldset>'            
            + '<thead>'
            + '<tr>'
            + '<th colspan="6" class="dt-responsive" style="text-align: center;">'
            + '<label class="font-size">Mapa Actualizaci&oacute;n Geozona</label>'
            + '</th>'
            + '</tr>'
            + '<tbody>'
            + '<tr>'
            + '<td colspan="6">'
            + '<div class="parte">'
            + '<label class="font-size">Zona Anterior</label>'
            + '<div id="divMapGeozonaAnterior"></div>'
            + '</div>'
            + '<div class="parte">'
            + '<label class="font-size">Zona Nueva</label>'
            + '<div id="divMapGeozonaNueva"></div>'
            + '</div>'
            + '</td>'
            + '</tr>'
            + '</tbody>'
            + '<thead>'
            + '<tr>'
            + '<th class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size"> <span class="req">*</span> Nombre Zona</label>'
            + '</th>'
            + '<th class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size">Color de la zona</label>'
            + '</th>'
            + '<tbody>'
            + '<tr>'
            + '<td>'
            + '<input type="text" id="txtZona" name="txtZona" class="required form-control col-xs-1 input-sm" onkeypress="mayuscula(this);" />'
            + '</td>'
            + '<td>'
            + '<p id="container"></p>'
            + '<input type="hidden" id="txtPos1" name="txtPos1"/>'
            + '<input type="hidden" id="txtPos2" name="txtPos2"/>'
            + '<input type="hidden" id="txtPos3" name="txtPos3"/>'
            + '<input type="hidden" id="txtPos4" name="txtPos4"/>'
            + '<input type="hidden" id="txtPos5" name="txtPos5"/>'
            + '</td>'
            + '</tbody>'
            + '</table>'
            + '</fieldset>'
            + '<div style="text-align:  center;">'
            + '<button type="button" class="btn" id="btnRegistrar" name="btnRegistrar" disabled="disabled">'
            + '<img src="../web/images/guardar.png" > Guardar </button>'
            + '<button type="button" class="btn" id="btnActualizar" name="btnActualizar">'
            + '<img src="../web/images/actualizar.png" > Actualizar </button>'
            + '<button type="button" class="btn" id="btnEliminar" name="btnEliminar" style="display: display;" disabled="disabled">'
            + '<img src="../web/images/eliminar.png" > Eliminar </button>'
            + '<button type="button" class="btn" id="btnCancel" name="btnCancel">'
            + '<img src="../web/images/cancel.png" > Cerrar </button>'
            + '</div>'
            + '</form>';
}

