function getFormVehiculo() {
    return  '<form id="frmVehiculo" name="frmVehiculo" method="post">'
            + '<input type="hidden" id="txtIdVehiculo" name="txtIdVehiculo" />'
            + '<div class="col-lg-6 col-md-4 col-sm-6 col-xs-12">'
            + '<div class="table-responsive">'
            + '<fieldset>'
            + '<legend class="text-muted alert-info">'
            + '<img src="../web/images/menuCliente.png" width="22px" height="22px">'
            + '<label class="font-size">Datos Cliente</label>'
            + '</legend>'
            + '<table class="table table-striped table-bordered dt-responsive nowrap display">'
            + '<thead>'
            + '<tr>'
            + '<th class="alert-info" style="text-align: center">'
            + '<label class=" font-size">Cliente</label></th>'
            + '</tr>'
            + '</thead>'
            + '<tbody>'
            + '<tr>'
            + '<td>'
            + '<select id="cboCliente" name="cboCliente" class="required form-control col-xs-1 input-sm">'
            + '</select>'
            + '</td>'
            + '</tr>'
            + '</tbody>'
            + '</table>'
            + '</fieldset>'
            + '</div>'
            + '</div>'
            + '<div class="col-lg-6 col-md-4 col-sm-6 col-xs-12">'
            + '<div class="table-responsive">'
            + '<fieldset>'
            + '<legend class="text-muted alert-info">'
            + '<img src="../web/images/nuevoGps.png">'
            + '  <label class="font-size">Datos Gps</label>'
            + '</legend>'
            + '  <table class="table table-striped table-bordered dt-responsive nowrap">'
            + '  <thead>'
            + '  <tr>'
            + '  <th class="alert-info" style="text-align: center">'
            + '  <label class="font-size"><span class="req">*</span> IMEI</label>'
            + '</th>'
            + '  <th class="alert-info" style="text-align: center">'
            + '  <label class="font-size"><span class="req">*</span> N<sup>o</sup> Sim</label>'
            + '</th>'
            + '  <th class="alert-info" style="text-align: center">'
            + '  <label class="font-size"><span class="req">*</span> Dispositivo Gps</label>'
            + '</th>'
            + ' </tr>'
            + '</thead>'
            + '<tbody>'
            + '<td>'
            + '<input type="text" id="txtImei" name="txtImei" class="required form-control col-xs-1 input-sm" onkeypress="mayuscula(this);"/>'
            + '</td>'
            + '<td>'
            + '<input type="text" id="txtTelefono" name="txtTelefono" class="required form-control col-xs-1 input-sm" onkeypress="mayuscula(this);"/>'
            + '</td>'
            + '<td>'
            + '<div class="form-group">'
            + '<select id="cboGps" name="cboGps" class="required form-control col-xs-1 input-sm">'
            + '</select>'
            + '</div>'
            + '</td>'
            + '</tbody>'
            + '</table>'
            + '</fieldset>'
            + '</div>'
            + '</div>'
            + '<div class="col-lg-7 col-md-4 col-sm-6 col-xs-12">'
            + '<div class="table-responsive">'
            + '<fieldset>'
            + '<legend class="text-muted alert-info">'
            + '<img src="../web/images/nuevoVehiculo.png">'
            + '<label class="font-size">Datos Veh&iacute;culo</label>'
            + '</legend>'
            + '<table class="table">'
            + '<thead>'
            + '<tr>'
            + '<th class="alert-info" style="text-align: center">'
            + '<label class="font-size"><span class="req">*</span> Modelo </label>'
            + '</th>'
            + '<th class="alert-info" style="text-align: center">'
            + '<label class="font-size"><span class="req">*</span> Marca</label>'
            + '</th>'
            + '<th class="alert-info" style="text-align: center">'
            + '<label class="font-size"><span class="req">*</span> Placa</label>'
            + '</th>'
            + '</tr>'
            + '</thead>'
            + '<tbody>'
            + '<tr>'
            + '<td>'
            + '<input type="text" id="txtModelo" name="txtModelo" class="required form-control col-xs-1 input-sm" onkeypress="mayuscula(this);"/>'
            + '</td>'
            + '<td>'
            + '<input type="text" id="txtMarca" name="txtMarca" class="required form-control col-xs-1 input-sm" onkeypress="mayuscula(this);"/>'
            + '</td>'
            + '<td>'
            + '<input type="text" id="txtPlaca" name="txtPlaca" class="required form-control col-xs-1 input-sm" onkeypress="mayuscula(this);"/>'
            + '</td>'
            + '</tr>'
            + '</tbody>'
            + '<thead>'
            + '<tr>'
            + '<th class="alert-info" style="text-align: center">'
            + '<label class="font-size">Color</label>'
            + '</th>'
            + '<th class="alert-info" style="text-align: center">'
            + '<label class="font-size">'
            + '<span class="req">*</span> &Uacute;ltima Verificaci&oacute;n'
            + '</label>'
            + '</th>'
            + '<th class="alert-info" style="text-align: center">'
            + '<label class="font-size"><span class="req">*</span> Tpo Uso</label>'
            + '</th>'
            + '</tr>'
            + '</thead>'
            + '<tbody>'
            + '<tr>'
            + '<td>'
            + '<input type="text" id="txtColor" name="txtColor" class="form-control col-xs-1 input-sm" onkeypress="mayuscula(this);" />'
            + '</td>'
            + '<td>'
            + '<input type="text" id="dtpVerificacion" name="dtpVerificacion" class="required form-control col-xs-1 input-sm" onkeypress="mayuscula(this);"/>'
            + '</td>'
            + '<td>'
            + '<div class="form-group">'
            + '<select id="cboGiro" name="cboGiro" class="required form-control col-xs-1 input-sm">'
            + '</select>'
            + '</div>'
            + '</td>'
            + '</tr>'
            + '</tbody>'
            + '<thead>'
            + '<tr>'
            + '<th colspan="3" class="alert-info" style="text-align: center">'
            + '<label class="font-size">Icono Veh&iacute;culo</label>'
            + '</th>'
            + '</tr>'
            + '</thead>'
            + '<tbody>'
            + '<tr>'
            + '<td class="dt-responsive">'
            + '<input type="checkbox" id="chkIcon" name="chkIcon" class="form-control col-xs-1 input-sm" onclick="show();">'
            + '</td>'
            + '</tr>'
            + '<tr>'
            + '<td class="dt-responsive" colspan="3">'
            + '<div id="divIcons" style="display: none;">'
            + '<div id="carousel" class="carousel slide" data-ride="carousel">'
            + '<div id="divContenido" class="carousel-inner" role="listbox">'
            + '</div>'
            + '<a class="left carousel-control" href="#carousel" role="button" data-slide="prev">'
            + '<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>'
            + '<span class="sr-only">Anterior</span>'
            + '</a>'
            + '<a class="right carousel-control" href="#carousel" role="button" data-slide="next">'
            + '<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>'
            + '<span class="sr-only">Siguiente</span>'
            + '</a>'
            + '</div>'
            + '</div>'
            + '<input type="hidden" id="txtIdImage" name="txtIdImage" value="<?php echo($default); ?> " />'
            + '</td>'
            + '</tr>'
            + '</tbody>'
            + '</table>'
            + '</fieldset>'
            + '</div>'
            + '</div>'
            + '<div class="col-lg-5 col-md-4 col-sm-6 col-xs-12">'
            + '<div class="table-responsive">'
            + '<fieldset>'
            + '<legend class="text-muted alert-info">'
            + '<img src="../web/images/activoInactivo.png">'
            + '<label class="font-size">Registro Activo / Inactivo</label>'
            + '</legend>'
            + '<table class="table">'
            + '<tbody>'
            + '<tr>'
            + '<td>'
            + '<input type="checkbox" id="chkActivo" name="chkActivo"'
            + 'class="checkbox-inline text-muted col-xs-1 input-sm" checked="checked" onclick="return false">'
            + '<label id="lblActivo" class="font-size">S&iacute;</label>'
            + '</td>'
            + '</tr>'
            + '</tbody>'
            + '</table>'
            + '</fieldset>'
            + '</div>'
            + '</div>'
            + '<div class="col-lg-12 col-md-4 col-sm-6 col-xs-12">'
            + '<div style="text-align:  center;">'
            + '<button type="button" class="btn" id="btnRegistrar" name="btnRegistrar">'
            + '<img src="../web/images/guardar.png">Guardar</button>'
            + '<button type="button" class="btn" id="btnActualizar" name="btnActualizar">'
            + '<img src="../web/images/actualizar.png">Actualizar</button>'
            + '<button type="button" class="btn" id="btnEliminar" name="btnEliminar" style="display: display;">'
            + '<img src="../web/images/eliminar.png">Inhabilitar</button>'
            + '<button type="button" class="btn" id="btnActivate" name="btnActivate" style="display: none;">'
            + '<img src="../web/images/habilitar.png">Habilitar</button>'
            + '<button type = "button" class="btn" id = "btnCancel" name = "btnCancel">'
            + '<img src = "../web/images/cancel.png" > Cerrar </button>'
            + '</div>'
            + '</div>'
            + '</form>';
}