function getFormGeoruta() {
    return   '<form id="frmGeoRuta" name="frmGeoRuta" method="post">'
            + '<input type="hidden" id="txtIdRuta" name="txtIdRuta" />'
            + '<div class="table-responsive">'
            + '<fieldset>'
            + '<table class="table" style="height: 100%;">'
            + '<thead>'
            + '<tr>'
            + '<th colspan="6" class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size"><span class="req">*</span> Colonia</label>'
            + '</th>'
            + '</tr>'
            + '</thead>'
            + '<tbody>'
            + '<tr>'
            + '<td colspan="6">'
            + '<input type="text" id="txtColonia" name="txtColonia" class="letras required form-control" style="width: 600px;" onkeypress="mayuscula(this);"/>'
            + '<input type="hidden" id="txtDataColoniaGr" name="txtDataColoniaGr" class="letras required form-control" readonly="readOnly"/>'
            + '<br/><label id="errorGeocoder" style="display: none;" class=" font-size alert-danger"></label>'
            + '</td>'
            + '</tr>'
            + '<tr>'
            + '</tr>'
            + '</tbody>'
            + '<thead>'
            + '<tr>'
            + '</tr>'
            + '</thead>'
            + '<tbody>'
            + '<tr>'
            + '<td colspan="6">'
            + '<div id="divMapGeoruta"></div>'
            + '</td>'
            + '</tr>'
            + '</tbody>'
            + '<thead>'
            + '<tr>'
            + '<th class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size">Veh&iacute;culos</label>'
            + '</th>'
            + '<th class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size"> <span class="req">*</span> Nombre Ruta</label>'
            + '</th>'
            + '<th class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size">Color de la ruta</label>'
            + '</th>'
            + '</tr>'
            + '</thead>'
            + '<tbody>'
            + '<tr>'
            + '<td>'
            + '<select class="form-control required" multiple="multiple" id="cboVehiculos" name="cboVehiculos">'
            + listVehiculos
            + '</select><label id="lblErrorSelect" style="display: none;" class="alert-danger font-size">Campo requerido</label>'
            + '<input type="hidden" id="txtLength" name="txtLength" readonly="readOnly" />'
            + '</td>'
            + '<td>'
            + '<input type="text" id="txtRuta" name="txtRuta" class="required form-control col-xs-1 input-sm" onkeypress="mayuscula(this);" />'
            + '</td>'
            + '<td>'
            + '<div id="container" style="margin: 0px 0px 0px 80px;"></div>'
            + '</td>'
            + '</tr>'
            + '</tbody>'
            + '</table>'
            + '<table id="tblCoordenadasGr" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" style="display: none; width: 40%;">'
            + '<tr></tr>'
            + '</table>'
            + '</fieldset>'
            + '<div style="text-align:center;">'
            + '<button type="button" class="btn" id="btnRegistrarRuta" name="btnRegistrarRuta">'
            + '<img src="../web/images/guardar.png"> Guardar </button>'
            + '<button type="button" class="btn" id="btnActualizarRuta" name="btnActualizarRuta">'
            + '<img src="../web/images/actualizar.png"> Actualizar </button>'
            + '<button type="button" class="btn" id="btnEliminarRuta" name="btnEliminarRuta" style="display: display;">'
            + '<img src="../web/images/eliminar.png" > Eliminar </button>'
            + '<button type="button" class="btn" id="btnAsociarRuta" name="btnAsociarRuta">'
            + '<img src="../web/images/vehiculoMapa.png" height="32px" width="32px;"> Asociar </button>'
            + '<button type="button" class="btn" id="btnCancelRuta" name="btnCancelRuta">'
            + '<img src="../web/images/cancel.png" > Cerrar </button>'
            + '</div>'
            + '</form>';
}

function getFormGeorutaUpdate() {
    return   '<form id="frmGeoRuta" name="frmGeoRuta" method="post">'
            + '<input type="hidden" id="txtIdRuta" name="txtIdRuta" />'
            + '<input type="hidden" id="txtLength" name="txtLength" readonly="readOnly" />'
            + '<div class="table-responsive">'
            + '<fieldset>'
            + '<table class="table" style="height: 100%;">'
            + '<thead>'
            + '<tr>'
            + '<th colspan="6" class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size"><span class="req">*</span> Colonia</label>'
            + '</th>'
            + '</tr>'
            + '</thead>'
            + '<tbody>'
            + '<tr>'
            + '<td colspan="6">'
            + '<input type="text" id="txtColonia" name="txtColonia" class="letras required form-control" style="width: 600px;" onkeypress="mayuscula(this);"/>'
            + '<input type="hidden" id="txtDataColoniaGr" name="txtDataColoniaGr" class="letras required form-control" readonly="readOnly"/>'
            + '</td>'
            + '</tr>'
            + '<tr>'
            + '<td>'
            + '<label id="errorGeocoder" style="display: none;" class="alert-danger"></label>'
            + '</td>'
            + '</tr>'
            + '</tbody>'
            + '<thead>'
            + '<tr>'
            + '</tr>'
            + '</thead>'
            + '<tbody>'
            + '<tr>'
            + '<td colspan="6">'
            + '<div class="parte">'
            + '<label class="font-size">Ruta Anterior</label>'
            + '<div id="divMapGeorutaAnterior"></div>'
            + '</div>'
            + '<div class="parte">'
            + '<label class="font-size">Ruta Nueva</label>'
            + '<div id="divMapGeoruta" style="width:100%; height:250px;"></div>'
            + '</div>'
            + '</tr>'
            + '</tbody>'
            + '<thead>'
            + '<tr>'
            + '<th class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size"> <span class="req">*</span> Nombre Ruta</label>'
            + '</th>'
            + '<th class="dt-responsive alert-info" style="text-align: center;">'
            + '<label class="font-size">Color de la ruta</label>'
            + '</th>'
            + '</tr>'
            + '</thead>'
            + '<tbody>'
            + '<tr>'
            + '<td>'
            + '<input type="text" id="txtRuta" name="txtRuta" class="required form-control col-xs-1 input-sm" onkeypress="mayuscula(this);" />'
            + '</td>'
            + '<td>'
            + '<div id="container"></div>'
            + '</td>'
            + '</tr>'
            + '</tbody>'
            + '</table>'
            + '<table id="tblCoordenadasGr" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" style="display: none; width: 40%;">'
            + '<tr></tr>'
            + '</table>'
            + '</fieldset>'
            + '<div style="text-align:center;">'
            + '<button type="button" class="btn" id="btnRegistrarRuta" name="btnRegistrarRuta">'
            + '<img src="../web/images/guardar.png"> Guardar </button>'
            + '<button type="button" class="btn" id="btnActualizarRuta" name="btnActualizarRuta">'
            + '<img src="../web/images/actualizar.png"> Actualizar </button>'
            + '<button type="button" class="btn" id="btnEliminarRuta" name="btnEliminarRuta" style="display: display;">'
            + '<img src="../web/images/eliminar.png" > Eliminar </button>'
            + '<button type="button" class="btn" id="btnAsociarRuta" name="btnAsociarRuta">'
            + '<img src="../web/images/vehiculoMapa.png" height="32px" width="32px;"> Asociar </button>'
            + '<button type="button" class="btn" id="btnCancelRuta" name="btnCancelRuta">'
            + '<img src="../web/images/cancel.png" > Cerrar </button>'
            + '</div>'
            + '</form>';
}